---
- name: Create the application Docker network
  community.docker.docker_network:
    name: "{{ docker_network_name }}"
    state: present
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python
